plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

group = 'com.cleanroommc'
version = '0.8.0'

repositories {
    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net/'
    }
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'commons-io:commons-io:2.15.1'
    implementation 'commons-codec:commons-codec:1.16.0'
    implementation 'org.apache.commons:commons-lang3:3.18.0'
    implementation 'io.github.java-diff-utils:java-diff-utils:4.15'
    implementation 'org.ow2.asm:asm:9.6'
    implementation 'org.ow2.asm:asm-commons:9.6'
    implementation 'org.ow2.asm:asm-tree:9.6'
    implementation 'org.ow2.asm:asm-util:9.6'
    implementation 'de.undercouch.download:de.undercouch.download.gradle.plugin:5.6.0'
    implementation 'de.siegmar:fastcsv:3.0.0'

    // CleanroomGradleSettings
    implementation 'org.gradle.toolchains:foojay-resolver:1.0.0'

    // Forge Toolchain
    implementation 'net.minecraftforge:srgutils:0.5.3'
    implementation 'net.minecraftforge:renamer-gradle:1.1.5'

    testImplementation gradleTestKit()
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

gradlePlugin {
    plugins {
        cleanroomGradle {
            id = "${group}.cleanroomgradle"
            implementationClass = "${group}.gradle.CleanroomGradle"
            displayName = 'CleanroomGradle'
            description = 'Gradle plugin for Cleanroom and Cleanroom-targeted mod development'
        }
        cleanroomGradleSettings {
            id = "${group}.cleanroomgradle.settings"
            implementationClass = "${group}.gradle.CleanroomGradleSettings"
            displayName = 'CleanroomGradle Settings'
            description = 'Settings plugin that injects Cleanroom dependency repositories and the Foojay toolchain resolver'
        }
    }
}

jar {
    manifest {
        attributes 'Implementation-Version': version
    }
}

test {
    useJUnitPlatform()
    systemProperty 'plugin.project.dir', rootDir.absolutePath
}

publishing {
    publications {
        pluginMaven(MavenPublication) {
            artifactId = 'cleanroomgradle'
        }
    }
    repositories {
        maven {
            name = 'CleanroomMaven'
            url = 'https://repo.cleanroommc.com/releases'
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}
